version: '3'

services:
  pxl-todo-app:
    image: pxl-todo-app
    ports:
      - "8080:3000"
    networks:
      - my-network

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secureRootPassword
      MYSQL_DATABASE: DB
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
    networks:
      - my-network

networks:
  my-network:
    driver: bridge